version: '3'
services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - ./migration/base.sql:/docker-entrypoint-initdb.d/base.sql
    networks:
      - my-network
networks:
  my-network: